services:
  express-app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - RABBITMQ_URL=amqp://rabbitmq
    networks:
      - net-app

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Porta do protocolo AMQP (Node vai usar essa)
      - "15672:15672" # Painel web do RabbitMQ
    networks:
      - net-app

networks:
  net-app:
    driver: bridge